<a href="https://colab.research.google.com/github/christinearroyo/csst101-arroyo/blob/main/Arroyo_RProgramming_CSST101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Creating Variable

In [ ]:
attendance_rate <- 0.82
average_grade <- 0.78

print(attendance_rate)
print(average_grade)

[1] 0.82
[1] 0.78

2. Basic Calculations

In [ ]:
quiz <- 85
laboratory <- 90
project <- 88
exam <- 80

quiz_weight <- 0.20
lab_weight <- 0.25
project_weight <- 0.25
exam_weight <- 0.30

grade <- (quiz * quiz_weight) +
         (laboratory * lab_weight) +
         (project * project_weight) +
         (exam * exam_weight)

print(grade)

cat("Weighted Final Grade:", grade)

[1] 85.5
Weighted Final Grade: 85.5

3. Using Comparison Operators

In [ ]:
attendance <- 0.72
grade <- 0.70

if (attendance < 0.75) {
  print("Attendance is below 75.")
} else {
  print("Attendance is at least 75.")
}

if (grade < 0.75) {
  print("Grade is below 75.")
} else {
  print("Grade is at least 75.")
}

[1] "Attendance is below 75."
[1] "Grade is below 75."

4. Using AND and OR

In [ ]:
attendance_rate <- 0.82
average_grade <- 0.78

if (attendance_rate < 0.75 && average_grade < 0.75) {
  print("Both Attendance and Grade are below 75.")
} else if (attendance_rate < 0.75 || average_grade < 0.75) {
  print("Either Attendance or Grade is below 75.")
} else {
  print("Both Attendance and Grade are at least 75.")
}

[1] "Both Attendance and Grade are at least 75."

5. Simple IF Statement

In [ ]:
grade <- 0.76

if (grade > 0.75) {
    print("Pass")
} else
    print("Fail")

[1] "Pass"

6. Multiple Conditions

In [ ]:
grade <- 0.78

if (grade > 0.90) {
  print("Excellent")
} else if (grade > 0.85 && grade <= 0.89) {
  print("Very Good")
} else if (grade > 0.80 && grade <= 0.84) {
  print("Good")
} else if (grade > 0.75 && grade <= 0.79) {
  print("Passed")
} else {
  print("Failed")
}

[1] "Passed"

7. Creating a Function

In [ ]:
classify_grade <- function(grade){
  if (grade >= 0.90) {
    print("Excellent")
  } else if (grade >= 0.85) {
    print("Very Good")
  } else if (grade >= 0.80) {
    print("Good")
  } else if (grade >= 0.75) {
    print("Passed")
  } else {
    print("Failed")
  }
}

classify_grade(0.75)

[1] "Passed"

8. Creating a Data Frame

In [ ]:

students <- data.frame(
Student_ID = c("S001", "S002","S003","S004","S005"),
Attendance = c("95","72","88","79","68"),
Grade = c("90","70","85","77","65")
)

students

  Student_ID Attendance Grade
1 S001       95         90
2 S002       72         70
3 S003       88         85
4 S004       79         77
5 S005       68         65

9. Adding a Classification Column

In [ ]:
students$Performance <- ifelse(
  students$Grade >= 80, "Good",
  ifelse(students$Grade >= 75, "Passed", "Failed")
)

students

  Student_ID Attendance Grade Performance
1 S001       95         90    Good
2 S002       72         70    Failed
3 S003       88         85    Good
4 S004       79         77    Passed
5 S005       68         65    Failed

10. Creating a Simple Rule-Based System

In [ ]:
if (attendance < 75 && grade < 75) {
  print("High Risk")
} else {
  print("Low Risk")
}

[1] "High Risk"

11. Add More Rules

In [71]:
student_risk <- function(attendance, grade) {
  if (attendance < 75 & grade < 75) {
    return("High Risk")
  }
  else if (attendance < 85 || grade < 80) {
    return("Moderate Risk")
  }
  else {
    return("Low Risk")
  }
}

students <- data.frame(
  Student_ID = c("S001", "S002", "S003", "S004", "S005"),
  Attendance = c(95, 72, 88, 79, 68),
  Grade = c(90, 70, 85, 77, 65)
)


students$Risk <- mapply(
  student_risk,
  students$Attendance,
  students$Grade
)

students

  Student_ID Attendance Grade Risk
1 S001       95         90    Low Risk
2 S002       72         70    High Risk
3 S003       88         85    Low Risk
4 S004       79         77    Moderate Risk
5 S005       68         65    High Risk

12. Count the Results

In [72]:
table(students$Risk)

    High Risk      Low Risk Moderate Risk
            2             2             1

1. There are 2 students classified as High Risk.
2. There is 1 students classified as Moderate Risk.
3. There are 2 students classified as Low Risk.
4. The High Risk and Low Risk groups are tied for having the largest number of students, with 2 students each.r

13. Create a Visualization

1. The graph shows the distribution and total count of students across each risk category.
2. Base on the data set, High Risk and Low Risk are tied for having the most students, with 2 in each category.
3. The university should implement targeted academic interventions and support programs for students in the High and Moderate Risk categories to help improve their attendance and grades.

14. Add a Recommendation

In [64]:
get_recommendation <- function(risk_level) {
  if (risk_level == "High Risk") {
    return("Immediate academic intervention")
  } else if (risk_level == "Moderate Risk") {
    return("Academic monitoring")
  } else {
    return("Continue regular monitoring")

  }
}

students$Recommendation <- sapply(students$Risk, get_recommendation)

students

  Student_ID Attendance Grade Risk      Recommendation
1 S001       95         90    Low Risk  Continue regular monitoring
2 S002       72         70    High Risk Immediate academic intervention
3 S003       88         85    Low Risk  Continue regular monitoring
4 S004       79         77    Low Risk  Continue regular monitoring
5 S005       68         65    High Risk Immediate academic intervention

15. Final System

In [79]:
evaluate_student <- function(student_id, attendance, grade) {
  if (attendance < 75 || grade < 75) {
    risk_level <- "High Risk"
    recommendation <- "Immediate academic intervention"
  } else if (attendance < 85 || grade < 85) {
    risk_level <- "Moderate Risk"
    recommendation <- "Monitor progress and offer support"
  } else {
    risk_level <- "Low Risk"
    recommendation <- "On track"
  }

  cat("Student ID:", student_id, "\n")
  cat("Attendance:", paste0(attendance, "%"), "\n")
  cat("Grade:", grade, "\n\n")
  cat("Risk Level:", risk_level, "\n\n")
  cat("Recommendation:\n")
  cat(recommendation, "\n")
}

evaluate_student(student_id = "S002", attendance = 72, grade = 70)

Student ID: S002
Attendance: 72%
Grade: 70

Risk Level: High Risk

Recommendation:
Immediate academic intervention