<a href="https://colab.research.google.com/github/christinearroyo/csst101-arroyo/blob/main/myFirstRProgram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. My First R Programming

In [ ]:
myString <- "I Love R Programming"

print(myString)

[1] "I Love R Programming"

2. Variable and Data Types

In [ ]:
myString <- "I Love R Programming"
wholeNum <- 10
floatingNum <- 9.9
isBool <- TRUE

print(myString)

[1] "I Love R Programming"

3. Numerical Operations

In [ ]:
x <- 10
y <- 3

add <- x + y
sub <- x - y
mul <- x * y
div <- x / y

print(add)
print(sub)
print(mul)
print(div)

[1] 13
[1] 7
[1] 30
[1] 3.333333

4. User Input

In [ ]:
name <- readline("Enter name: ")

cat("Welcome to R Programming: ", name)

Enter name: Christine
Welcome to R Programming:  Christine

5. Decision Making

In [ ]:
# grade <- 80

grade <- readline("Enter your grade: ")

if (grade < 75){
 print ("Failed")
}else {
 print ("Passed")
}

Enter your grade: 81
[1] "Passed"

6. Loop

In [ ]:
for ( i in 1:5){
 print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

7. Function

In [ ]:
addNumber <- function(a,b){
 return (a+b)
}

addNumber(3,7)

[1] 10

8. Vectors

In [ ]:
grades <- c(98,80,91,88,96)

grades

cat("Mean: ",mean(grades))
cat("\nMax: ",max(grades))
cat("\nMin: ",min(grades))
cat("\nLength: ",length(grades))
cat("\nMedian: ",median(grades))
summary(grades)

[1] 98 80 91 88 96

Mean:  90.6
Max:  98
Min:  80
Length:  5
Median:  91

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   80.0    88.0    91.0    90.6    96.0    98.0

9. Matrices

In [ ]:
A <- matrix(c(1,2,3,4,5,6), nrow=2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

10. Lists

In [ ]:
students <- list(
Name = "Christine",
Course = "BSCS",
Grade = "85"
)

students

$Name
[1] "Christine"

$Course
[1] "BSCS"

$Grade
[1] "85"

11. Dataframe

In [ ]:
students <- data.frame(
name = c("Tin","Manuel","Jay"),
course = c("BSCS","BSIT","BSIS"),
grade = c(75,85,95)
)

students

  name   course grade
1 Tin    BSCS   75
2 Manuel BSIT   85
3 Jay    BSIS   95

12. Write to CSV

In [30]:
#save dataframe to csv.file
write.csv(students,"students.csv")

13. Read CSV File

In [31]:
data <- read.csv("students.csv")

head(summary)
summary(data)

1 function (object, ...)
2 UseMethod("summary")

       X              name         course      grade
 Min.   :1.0   Length   :3   Length   :3   Min.   :75
 1st Qu.:1.5   N.unique :3   N.unique :3   1st Qu.:80
 Median :2.0   N.blank  :0   N.blank  :0   Median :85
 Mean   :2.0   Min.nchar:3   Min.nchar:4   Mean   :85
 3rd Qu.:2.5   Max.nchar:6   Max.nchar:4   3rd Qu.:90
 Max.   :3.0                               Max.   :95

My Test Code Environment

In [ ]:
firstName <- readline("First Name: ")
lastName <- readline("Last Name: ")

ageRestrict <- readline("Age: ")

if (ageRestrict < 18){
 print("Get out of my system your underage.")
}else {
 print("Good thing your an adult.")
}

intFirstName <- as.integer(firstName)
for (i in intFirstName){
 print("Amount of your First Name letters.")
 print(i)
}

First Name: Christine
Last Name: Arroyo
Age: 20
[1] "Good thing your an adult."

Warning message:
“NAs introduced by coercion”

[1] "Amount of your First Name letters."
[1] NA